Repository atlanhq/atlan-go, pull requests merged in 2024-06, with the labels that each got.

#40 DVX-525: Fixed missing "description" in the `SearchAttributes` struct
  atlan/assets/fluent_search_test.go
  atlan/assets/glossary_client.go
  atlan/model/search.go
Labels: bug

#39 Migrate from dataContractJson to dataContractSpec
  atlan/model/structs/datacontract.go
Labels: feature

#42 Bump to release `0.0.2`
  VERSION
Labels: release
