Repository atlanhq/atlan-go, pull requests merged in 2025-01, with the labels that each got.

#72 FT-803 : Manage `Users` and `Groups`
  atlan/assets/client.go
  atlan/assets/constants.go
  atlan/assets/group_client.go
  atlan/assets/group_client_test.go
  atlan/assets/role_cache.go
  atlan/assets/role_client.go
  atlan/assets/user_client.go
  atlan/assets/user_client_test.go
  atlan/model/structs/group.go
  atlan/model/structs/role.go
  atlan/model/structs/user.go
  main.go
Labels: feature

#73 Bump to release `0.0.13`
  config/VERSION
Labels: release

#75 FT-585: Added Installation for development section to README.md
  .env.example
  .gitignore
  README.md
Labels: documentation

#74 FT-912 : Manage Tokens
  atlan/assets/client.go
  atlan/assets/constants.go
  atlan/assets/token_client.go
  atlan/assets/token_client_test.go
  atlan/model/structs/api_tokens.go
  main.go
Labels: feature

#79 FT-915 : Add template for pull request
  .github/PULL_REQUEST_TEMPLATE.md
Labels: QOL

#78 FT-807 : Manage Purposes
  atlan/assets/auth_policy_client.go
  atlan/assets/index_search_client.go
  atlan/assets/purpose_client.go
  atlan/assets/purpose_client_test.go
  atlan/model/search.go
  atlan/model/structs/access_control.go
  atlan/model/typedef.go
  main.go
Labels: feature

#81 Bump to release 0.0.14
  config/VERSION
Labels: release

#80 FT-463 : Integrate `golangci-lint` for Linting
  .github/workflows/golangci-lint.yml
  .gitignore
  .pre-commit-config.yaml
  atlan/assets/asset.go
  atlan/assets/atlan_fields.go
  atlan/assets/atlan_tag_cache.go
  atlan/assets/atlan_tag_cache_test.go
  atlan/assets/auth_policy_client.go
  atlan/assets/batch_processing.go
  atlan/assets/client.go
  atlan/assets/client_test.go
  atlan/assets/custom_metadata_cache.go
  atlan/assets/data_contract_client.go
  atlan/assets/errors.go
  atlan/assets/file.go
  atlan/assets/file_client_test.go
  atlan/assets/fluent_search.go
  atlan/assets/fluent_search_test.go
  atlan/assets/glossary_client.go
  atlan/assets/glossary_client_test.go
  atlan/assets/glossary_test.go
  atlan/assets/group_client.go
  atlan/assets/group_client_test.go
  atlan/assets/index_search_client.go
  atlan/assets/persona_client.go
  atlan/assets/persona_client_test.go
  atlan/assets/purpose_client.go
  atlan/assets/purpose_client_test.go
  atlan/assets/role_cache.go
  atlan/assets/role_client.go
  atlan/assets/table_client.go
  atlan/assets/token_client.go
  atlan/assets/token_client_test.go
  atlan/assets/typedef_client.go
  atlan/assets/typedef_client_test.go
  atlan/assets/user_client.go
  atlan/assets/user_client_test.go
  atlan/enums.go
  atlan/model/response.go
  atlan/model/structs/connection.go
  atlan/model/structs/glossary_term.go
  atlan/model/typedef.go
  config/.golangci.yaml
  main.go
Labels: QOL

#82 APP-5003 : Fixes maximum token TTE to 5 years
  atlan/assets/token_client_test.go
  atlan/model/structs/api_tokens.go
Labels: bug

#83 APP-5079 : Manage Policies
  atlan/assets/asset.go
  atlan/assets/atlan_fields.go
  atlan/assets/auth_policy_client.go
  atlan/assets/purpose_client.go
  atlan/model/search.go
  atlan/model/structs/access_control.go
  main.go
Labels: feature

#84 Bump to release `0.0.15`
  config/VERSION
Labels: release

#86 APP-5147 : Add DataMaskingType enums
  atlan/assets/auth_policy_client.go
  atlan/enums.go
  atlan/model/search.go
  atlan/model/structs/access_control.go
Labels: enhancement

#85 APP-5150 : Add `PurposeFields` for Searching through FluentSearch
  atlan/assets/asset.go
  atlan/assets/client.go
Labels: enhancement
